# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# OS & tools
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
    nodejs: "20"   # Optional if you have JS/TS projects
    rust: "1.80"   # Optional if you have Rust projects

# Use Sphinx for main docs
sphinx:
  configuration: docs/conf.py

# Install dependencies for docs build
python:
  install:
    - requirements: docs/requirements.txt
