name: "🐞 Bug report"
description: Report a bug with steps, expected vs actual, and evidence
title: "[Bug]: <short summary>"
labels: ["bug"]
projects:
  - GlobeTalk
assignees:
  - Momo3945
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug! Please fill in the details below.
        👉 You can **drag & drop screenshots/GIFs/videos** right into the “Evidence” box,
        or paste images from your clipboard. For larger videos, paste a link.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: One short sentence describing the bug
      placeholder: e.g. "Clicking Send does nothing on the messaging page"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - P0 — blocking / no workaround
        - P1 — major / workaround exists
        - P2 — moderate
      default: 2
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Numbered steps that consistently reproduce the issue
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
      render: bash
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected result
      placeholder: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual result
      placeholder: What actually happened (include any error text)
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: Evidence (screenshots / videos / GIFs)
      description: Drag & drop files or paste images directly here. For large videos, paste a link (e.g., Google Drive).
      placeholder: "Drop files here or paste images. Add links for big videos."
    validations:
      required: false

  - type: dropdown
    id: env
    attributes:
      label: Browser / App
      description: Which environment did this happen on?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Opera
        - Brave
        - iOS App
        - Android App
        - Other
    validations:
      required: true


  - type: checkboxes
    id: sanity
    attributes:
      label: Pre-submission checks
      options:
        - label: I searched existing issues and didn't find this bug.
          required: true
        - label: I can reproduce this on the latest version.
          required: false
