name: Bug intake
on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read
  projects: write  # required for Projects v2
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure bug label
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const hasBug = issue.labels.some(l => (typeof l === 'string' ? l : l.name) === 'bug');
            if (!hasBug) {
              await github.rest.issues.addLabels({
                ...context.repo,
                issue_number: issue.number,
                labels: ['bug']
              });
            }

      - name: Ensure assignee to Momo3945
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addAssignees({
              ...context.repo,
              issue_number: context.payload.issue.number,
              assignees: ['Momo3945']
            });

      - name: Add to GlobeTalk project (Project v2)
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/users/MuaazBayat/projects/4
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Evidence prompt for missing screenshots/videos
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.issue.body || '';
            const hasEmbed = /!\[.*\]\(.*\)/.test(body);
            const hasLink = /(https?:\/\/\S+\.(png|jpe?g|gif|mp4|mov|webm))/i.test(body);
            if (!hasEmbed && !hasLink) {
              await github.rest.issues.createComment({
                ...context.repo,
                issue_number: context.payload.issue.number,
                body: "👋 Please add a **screenshot** or **short video/GIF** to help us diagnose the issue. You can drag & drop files right into the issue."
              });
            }
