name: ☁️ Deploy Matchmaking to Cloud Run

env:
  TAG: ${{ github.event.release.tag_name || 'release-test' }}
  MATCHMAKING_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/globetalk-matchmaking:${{ github.event.release.tag_name || 'release-test' }}

on:
  release:
    types: [published]  # Trigger when a GitHub release is published

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Build & push Matchmaking Docker images
        run: |
          docker buildx build  --no-cache \
            --platform linux/amd64 \
            -t $MATCHMAKING_IMAGE \
            -f services/matchmaking/matchmaking.Dockerfile \
            services/matchmaking \
            --push

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      
      - name: Deploy matchmaking Cloud Run
        id: deploy-matchmaking
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: 'globetalk-matchmaking'
          image: ${{ env.MATCHMAKING_IMAGE }}
          flags: '--allow-unauthenticated --port=8000 --update-env-vars=[SUPABASE_URL=${{ secrets.SUPABASE_URL }},SUPABASE_KEY=${{ secrets.SUPABASE_KEY }},FRONTEND_URL=${{ secrets.FRONTEND_URL }},CORE_URL=${{ secrets.CORE_URL }},MATCHMAKING_URL=${{ secrets.MATCHMAKING_URL }},MESSAGING_URL=${{ secrets.MESSAGING_URL }},MODERATION_URL=${{ secrets.MODERATION_URL }},ENABLE_AUTH=true]'
          container_port: 8000

      - name: Show Output
        run: |
          echo "Deployment finished!"
          echo "Matchmaking deployed at:"
          echo "${{ steps.deploy-matchmaking.outputs.url }}"