import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/header";
import "./globals.css";
import { ConversationUserProvider } from "@/lib/context/ConversationUserContext";
import { ProfileProvider } from "@/lib/context/ProfileContext";
import { FpjsProvider } from "@fingerprintjs/fingerprintjs-pro-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <FpjsProvider
            loadOptions={{
              apiKey: process.env.NEXT_PUBLIC_FPJS_KEY || "",
              region: "eu",
            }}
          >
            <ProfileProvider>
              <ConversationUserProvider>
                <Header />
                {children}
              </ConversationUserProvider>
            </ProfileProvider>
          </FpjsProvider>
        </body>
      </ClerkProvider>
    </html>
  );
}
